DATA:
  IMG_SIZE: 480
PRETRAIN:
  PATH: checkpoint/swin_base_patch4_window12_384_22k.pth
MODEL:
  NAME: swin
  DROP_PATH_RATE: 0.3
  NUM_CLASSES: 21841
  SWIN:
    EMBED_DIM: 128
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 4, 8, 16, 32 ]
    WINDOW_SIZE: 12
